### ISSUE TITLE
找不到模型文件

### ISSUE THREAD

**Issue by zhenglong1997** [jingsongliujing/OnnxOCR#11]
我下载源码并安装完环境后，执行，出现Traceback (most recent call last):
  File "test_ocr.py", line 13, in <module>
    model = ONNXPaddleOcr(use_angle_cls=True, use_gpu=False)
  File "C:\Users\zheng\Desktop\OnnxOCR-main\onnxocr\onnx_paddleocr.py", line 27, in __init__
    super().__init__(params)
  File "C:\Users\zheng\Desktop\OnnxOCR-main\onnxocr\predict_system.py", line 17, in __init__
    self.text_classifier = predict_cls.TextClassifier(args)
  File "C:\Users\zheng\Desktop\OnnxOCR-main\onnxocr\predict_cls.py", line 17, in __init__
    self.cls_onnx_session = self.get_onnx_session(args.cls_model_dir, args.use_gpu)
  File "C:\Users\zheng\Desktop\OnnxOCR-main\onnxocr\predict_base.py", line 14, in get_onnx_session
    onnx_session = onnxruntime.InferenceSession(model_dir, None,providers=providers)
  File "C:\Users\zheng\miniconda3\envs\py38\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\zheng\miniconda3\envs\py38\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ./onnxocr/models/ppocrv4/cls/cls.onnx OnnxOCR-main\onnxocr\models\ppocrv4\cls\cls.onnx failed:Load model ./onnxocr/models/ppocrv4/cls/cls.onnx OnnxOCR-main\onnxocr\models\ppocrv4\cls\cls.onnx failed. File doesn't exist。我发现utils.py文件305行parser.add_argument("--cls_model_dir", type=str, default='./onnxocr/models/ppocrv4/cls/cls.onnx OnnxOCR-main\onnxocr\models\ppocrv4\cls\cls.onnx')出错，需要修改为parser.add_argument("--cls_model_dir", type=str, default='./onnxocr/models/ppocrv4/cls/cls.onnx')

**Comment by jingsongliujing** [comment]
这个问题和你本身的工程路径有关，尽量把onnxocr这个文件夹和test_ocr.py在同一目录

**Comment by zhenglong1997** [comment]
Thanks♪(･ω･)ﾉ
